name: akdraft
favicon: null
layout_spectrum: 0.37766
typography_spectrum: 0.5679890681058168
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.048206058563664556
  lightness: 0.5447132843546569
  saturation: 0.409685293212533
  rhythmicContrast: 0.764681251719594
purpose: []
